# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKeys',
        ),
    ]
